---
# handlers file for docker.ubuntu
- name: Start Docker
  service: name=docker state=started

- name: Reload docker
  service: name=docker state=reloaded

- name: Update certifcates
  shell: update-ca-certificates

- name: Restart docker
  action: service name=docker state=restarted

- name: Restart rsyslog
  action: service name=rsyslog state=restarted
